//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRequisiciones_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int Part { get; set; }
        public int Cantidad { get; set; }
        public int Unidad { get; set; }
        public string Descripcion { get; set; }
        public string Surtido { get; set; }
        public Nullable<int> NoRequisicion { get; set; }
    
        public virtual Requisiciones Requisiciones { get; set; }
    }
}
